### ISSUE TITLE
Link to Gammapy Twitter

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy-webpage#19]
We should add a link to  https://twitter.com/gammapyST and mention it as one way (besides the mailing list) to get notifications for Gammapy-related news.

- It should be listed here: http://gammapy.org/contact.html
- Also mentioned here: http://gammapy.org/news.html
- Also shows somehow with the Twitter symbol on the front-page or every page: http://gammapy.org/

**Comment by bkhelifi** [comment]
done.
