### ISSUE TITLE
Navbar show active page

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy-webpage#6]
Currently the navbar doesn't show the active page.

E.g. here "about" in the navbar isn't highlighted:
https://rawgit.com/robertazanin/gammapy-webpage/69c5a1625b60e2e45adb93ce6c95faf3ce3942cd/about.html

Example of what we want: https://getbootstrap.com/docs/4.0/examples/
there in the navbar "examples" is highlighted.

We want this, but ideally set up in a way so that a "variable" is defined in the `head` of each page saying which nav item is active, e.g. below
```
    <title>Gammapy - About</title>
```
This would then be easier to maintain, because for a navbar change one can then still simply copy & paste the whole navbar between the different html pages we have. Adding the "active" attribute directly in the navbar code is error-prone, quickly leads to copy & paste errors.

**Comment by bkhelifi** [comment]
This is added.
