### ISSUE TITLE
Finish about page

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy-webpage#9]
The current about page is [here](https://rawgit.com/robertazanin/gammapy-webpage/69c5a1625b60e2e45adb93ce6c95faf3ce3942cd/about.html).
The text there isn't reviewed / discussed.

In the docs we still have a much more extensive about page: http://docs.gammapy.org/en/latest/about.html

@bkhelifi - When you come to Heidelberg, we should finish the transition.

**Comment by bkhelifi** [comment]
Done,
